### ISSUE TITLE
Short hostname

### ISSUE THREAD

**Issue by aitorserra** [poralix/reCaptcha2_validation-free#10]
Hello,

I'm having a problem with a new server. The server it is using a "short" hostname, a change that was done from DA version 1.662: https://docs.directadmin.com/changelog/version-1.662.html#use-short-node-name-for-host-name-and-keep-fqdn-in-etc-hosts

This make that the URL for validation short: http://ns1/__captcha_validation/?ref=https://

Instead of the correct one: http://ns1.domain.com/__captcha_validation/?ref=https://

Is there any solution from your side? I also sent a ticket to DA support about that.

Thank you.

**Comment by aitorserra** [comment]
DA support point me to the solution at /etc/httpd/conf/extra/httpd-poralix-recaptcha.conf

**Comment by gralex54** [comment]
Hello,

Thank you for the reporting the issue. I've updated the installation scripts to use `hostname -f`. Will it work for you if you re-install the software?
