### ISSUE TITLE
Apache does not start after installation

### ISSUE THREAD

**Issue by paulonichio** [poralix/reCaptcha2_validation-free#3]
Hello;

I have a DirectAdmin server (apache_ngnix) and, after installing reCaptcha2_validation-free, it went down and never came back.

I tried to change from apache_ngnix to apache only, and even then, the server remained down.

The server only started working again after installing reCaptcha2_validation-free. What could it be?

This is the error it generated:

```
Apr 29 11:58:01 jupiter systemd: Starting The Apache HTTP Server...
Apr 29 11:58:01 jupiter httpd: httpd: Syntax error on line 157 of /etc/httpd/conf/httpd.conf: Syntax error on line 9 of /etc/httpd/conf/extra/httpd-includes.conf: Include takes one argument, Name(s) of the config file(s) to be included; fails if the wildcard does not match at least one file
Apr 29 11:58:01 jupiter systemd: httpd.service: main process exited, code=exited, status=1/FAILURE
Apr 29 11:58:01 jupiter kill: kill: cannot find process ""
Apr 29 11:58:01 jupiter systemd: httpd.service: control process exited, code=exited status=1
Apr 29 11:58:01 jupiter systemd: Failed to start The Apache HTTP Server.
Apr 29 11:58:01 jupiter systemd: Unit httpd.service entered failed state.
Apr 29 11:58:01 jupiter systemd: httpd.service failed.
```

Thank you.

**Comment by gralex54** [comment]
Hello,

It seems the file  `/etc/httpd/conf/extra/httpd-includes.conf`

was already populated with some code before you've installed the `reCaptcha2_validation-free` addon, And you were missing a break like. So you might need to check the file `/etc/httpd/conf/extra/httpd-includes.conf` and correct break-lines.

Regards,
Alex.
