### ISSUE TITLE
Not Redirecting in Cloudflare

### ISSUE THREAD

**Issue by Vsnumimmy** [poralix/reCaptcha2_validation-free#6]
Hello,
I had installed this script on cPanel Environment. If the domain uses Cloudflare it was not redirecting to the WP-Login page after Captcha solved.It was again showing the captcha confirmation page 

Please get an fix for it

**Comment by gralex54** [comment]
Hello,

I tested a domain of my own which is secured with CloudFlare, and everything worked correctly. I solved the captcha and could access a wp-login.php page.

Do you still have the issue under cPanel? With the latest version of the software?
