### ISSUE TITLE
How to disable cron notifications?

### ISSUE THREAD

**Issue by aitorserra** [poralix/reCaptcha2_validation-free#9]
Hello,

I'm looking for a method to stop the daily cron notifications form /etc/cron.daily/clear_recaptcha_ips.cron without breaking anything. How can I do it? Thank you.

**Comment by gralex54** [comment]
Hello,

You might change the following line in the file `/etc/cron.daily/clear_recaptcha_ips.cron`:

```
find ${DATA_DIR} -type f -mtime +${DAYS} -name _\*.dat -exec rm -v {} \;
```

and bring to the following view:

```
find ${DATA_DIR} -type f -mtime +${DAYS} -name _\*.dat -exec rm {} \;
```

That should do the trick.

Regards.

**Comment by aitorserra** [comment]
Perfect! I changed it! thank you very much.
